title: "[문의] "
body:
  - type: markdown
    attributes:
      value: |
        > :warning: **Client Secret은 절대 입력하지 마세요. Client ID만 입력해 주세요.**

  - type: textarea
    id: inquiry
    attributes:
      label: "문의 내용"
      value: |
        - Client ID (Client Secret이 노출되지 않도록 주의하여 주세요) :
        - 서비스 URL:
        - 오류 현상:
        - 오류 발생 환경:
           - android? ios? pc?
           - 브라우져? 앱?
        - 오류 재현 스텝
           - 오류를 재현해보려면 어떤 절차로 진행해야 하는지 순서대로 적어주시면 빠른 원인 파악에 도움이 됩니다.
        - 짐작되는 원인:
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ### * 네이버로그인 뱃지가 노출이 안되는 경우
        - 네이버로그인 뱃지가 노출되지 않으면 다음의 사항을 확인해주세요.
           1) 개발자센터에 등록된 '서비스 URL'이 광고나 사이트 검색에 노출되는 URL과 동일한지 여부
           2) 일정 수준 이상의 사용자가 발생하는지 여부

        ### * 등록자 아이디 변경이 필요한 경우
        - [문의폼](https://help.naver.com/support/alias/naveridlogin/naveridlogin_03.naver)으로 접수해주세요.

        ### * 네이버로그인 영문 가이드가 필요한 경우
        - dl_naverid@navercorp.com 으로 문의 해주세요.

        ### * 서비스 설정에 오류가 있다는 메시지가 노출되는 경우
        - [도움말](https://help.naver.com/support/alias/naveridlogin/naveridlogin_02.naver)을 참고해 주세요.

        ### * 참고
        - [적용 가이드](https://developers.naver.com/products/login/userguide/)
        - [개발 가이드](https://developers.naver.com/docs/login/devguide/)
        - [검수 가이드](https://developers.naver.com/docs/login/verify/)
